<a href="https://colab.research.google.com/github/tsangrebecca/BloomTech/blob/main/Sprint_1/Module_2/O4_Understand_the_purpose_of_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

mms = pd.read_csv('https://tinyurl.com/mms-statistics')

display(mms.head())

            type   color  diameter  mass
0  peanut butter    blue     16.20  2.18
1  peanut butter   brown     16.50  2.01
2  peanut butter  orange     15.48  1.78
3  peanut butter   brown     16.32  1.98
4  peanut butter  yellow     15.59  1.62

In [2]:
import math

pie = math.pi
print(pie)

3.141592653589793

In [5]:
# add volume hence density columns to the data
# diameter is in mm, convert to cm

# create volume column
mms['volume_in_cm^3'] = (4/3)*(pie)*(mms['diameter']*0.1/2)**3

# Create density column
mms['density_in_g/cm^3'] = mms['mass']/mms['volume_in_cm^3']

# see the new columns
display(mms.head())

            type   color  diameter  mass  volume_in_cm^3  density_in_g/cm^3
0  peanut butter    blue     16.20  2.18        2.226095           0.979293
1  peanut butter   brown     16.50  2.01        2.352071           0.854566
2  peanut butter  orange     15.48  1.78        1.942278           0.916449
3  peanut butter   brown     16.32  1.98        2.275931           0.869974
4  peanut butter  yellow     15.59  1.62        1.983979           0.816541

In [6]:
# create radius column
mms['radius'] = mms['diameter']/2
mms.head()

,type,color,diameter,mass,volume_in_cm^3,density_in_g/cm^3,radius
0,peanut butter,blue,16.20,2.18,2.226095,0.979293,8.100
1,peanut butter,brown,16.50,2.01,2.352071,0.854566,8.250
2,peanut butter,orange,15.48,1.78,1.942278,0.916449,7.740
3,peanut butter,brown,16.32,1.98,2.275931,0.869974,8.160
4,peanut butter,yellow,15.59,1.62,1.983979,0.816541,7.795