<a href="https://colab.research.google.com/github/tsangrebecca/BloomTech/blob/main/Sprint7/Module1/O1_ChooseATargetToPredictAndCheckItsDistribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import libraries, load data, and view
import pandas as pd
url="https://raw.githubusercontent.com/bloominstituteoftechnology/DS-Unit-2-Kaggle-Challenge/main/data/weather/weatherAUS.csv"

weather=pd.read_csv(url)
weather.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [3]:
# Display the info for the weather DataFrame
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217143 entries, 0 to 217142
Data columns (total 24 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           217143 non-null  object
 1   Location       217143 non-null  object
 2   MinTemp        213597 non-null  float64
 3   MaxTemp        213784 non-null  float64
 4   Rainfall       210781 non-null  float64
 5   Evaporation    101279 non-null  float64
 6   Sunshine       92165 non-null   float64
 7   WindGustDir    200813 non-null  object
 8   WindGustSpeed  200920 non-null  float64
 9   WindDir9am     200103 non-null  object
 10  WindDir3pm     207905 non-null  object
 11  WindSpeed9am   212983 non-null  float64
 12  WindSpeed3pm   209412 non-null  float64
 13  Humidity9am    212294 non-null  float64
 14  Humidity3pm    208212 non-null  float64
 15  Pressure9am    193119 non-null  float64
 16  Pressure3pm    193138 non-null  float64
 17  Cloud9am       123473 non-null  float64
 18  Cloud3pm       117663 non-null  float64
 19  Temp9am        213519 non-null  float64
 20  Temp3pm        209360 non-null  float64
 21  RainToday      210781 non-null  object
 22  RISK_MM        210782 non-null  float64
 23  RainTomorrow   210782 non-null  object
dtypes: float64(17), object(7)
memory usage: 39.8+ MB

In [4]:
# Look at the 'outcome_type' column
weather['RainTomorrow'].value_counts()

No     164187
Yes     46595
Name: RainTomorrow, dtype: int64

In [5]:
# Look at the 'outcome_type' column
weather['RainTomorrow'].value_counts(normalize=True)

No     0.778942
Yes    0.221058
Name: RainTomorrow, dtype: float64